#!/bin/bash
rm cloud_parcel QLD_test.*
#rm eXparcel 
#test.out
make
#gfortran activation.F90 -o eXparcel
#./thiseX > stdout
if [ -f cloud_parcel ]; then
qsub run_cheyenne 
fi
#./cloud_parcel >stdout &
