#!/bin/bash
#PBS -N test_u5_maritime_dilu10
#PBS -l select=1:ncpus=1
#PBS -l walltime=00:15:00
#PBS -A P54048000 
#PBS -j oe
#PBS -q premium
#PBS -M sisichen@ucar.edu

## set directories
## set your executable file

## PBS -A P54048000
## PBS -A P48500028 
##HAP group account
## start the application

#module purge
export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR
export TMPDIR_WORK=/glade/u/home/sisichen/Github/parcel/QLD_newkappa
if [ ! -f $TIMDIR_WORK ];then
mkdir $TMPDIR_WORK
fi
cp cloud_parcel $TMPDIR_WORK/cloud_parcel_u5_maritime_dilu10
cp parameter.dat $TMPDIR_WORK/
cd $TMPDIR_WORK

time ./cloud_parcel_u5_maritime_dilu10 >stdout_u5_maritime_dilu10





