#!/bin/bash
#PBS -N QLD_case
#PBS -l select=1:ncpus=1
#PBS -l walltime=00:05:00
#PBS -A P54048000 
#PBS -j oe
#PBS -q premium
#PBS -M sisichen@ucar.edu

## set directories
## set your executable file

## PBS -A P54048000
## PBS -A P48500028 
##HAP group account
## start the application

#module purge

##source /glade/u/apps/ch/opt/Lmod/7.3.14/lmod/7.3.14/init/bash
#module load peak_memusage
#module load impi
#module load openmpi
#mpirun -n 32 ./cloud_turb > stdout_cheyenne
#export MPI_SHEPHERD=true 
#mpiexec_mpt peak_memusage.exe ./cloud_turb > stdout_cheyenne
time ./cloud_parcel >stdout
#mpirun -n $[PBS_NUM_NODES*ppn] -npernode $ppn $myExe
#mpiexec -n $[PBS_NUM_NODES*ppn] -npernode $ppn  $myExe > stdout
